CREATE TABLE "user" (
                        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nickname VARCHAR(200) NOT NULL,
                        email VARCHAR(200) NOT NULL,
                        password VARCHAR(200),
                        role VARCHAR(50) NOT NULL,
                        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT uk_user_email UNIQUE (email),
                        CONSTRAINT uk_user_nickname UNIQUE (nickname),
                        CONSTRAINT chk_user_role CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE flashcard_set (
                               set_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               set_name VARCHAR(100) NOT NULL,
                               description TEXT NOT NULL,
                               created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_flashcard_set_user
                                   FOREIGN KEY (user_id)
                                       REFERENCES "user" (user_id)
                                       ON DELETE CASCADE
);

CREATE TABLE flashcard (
                           flashcard_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           set_id BIGINT NOT NULL,
                           term TEXT NOT NULL,
                           definition TEXT NOT NULL,

                           CONSTRAINT fk_flashcard_flashcard_set
                               FOREIGN KEY (set_id)
                                   REFERENCES flashcard_set (set_id)
                                   ON DELETE CASCADE
);

CREATE INDEX idx_flashcard_sets_user_id ON flashcard_set (user_id);
CREATE INDEX idx_flashcards_set_id ON flashcard (set_id);