CREATE TABLE folder (
                        folder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        name VARCHAR(100) NOT NULL,
                        description TEXT,
                        created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT fk_folder_user
                            FOREIGN KEY (user_id)
                                REFERENCES "user" (user_id)
                                ON DELETE CASCADE
);

CREATE TABLE folder_flashcard_set (
                                      folder_id BIGINT NOT NULL,
                                      set_id BIGINT NOT NULL,

                                      PRIMARY KEY (folder_id, set_id),

                                      CONSTRAINT fk_folder_flashcard_set_folder
                                          FOREIGN KEY (folder_id)
                                              REFERENCES folder (folder_id)
                                              ON DELETE CASCADE,

                                      CONSTRAINT fk_folder_flashcard_set_set
                                          FOREIGN KEY (set_id)
                                              REFERENCES flashcard_set (set_id)
                                              ON DELETE CASCADE
);

CREATE INDEX idx_folder_user_id ON folder (user_id);
CREATE INDEX idx_folder_flashcard_set_folder_id ON folder_flashcard_set (folder_id);
CREATE INDEX idx_folder_flashcard_set_set_id ON folder_flashcard_set (set_id);