CREATE TABLE "user"
(
    user_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname   VARCHAR(200) NOT NULL,
    email      VARCHAR(200) NOT NULL,
    password   VARCHAR(200) DEFAULT NULL,
    role       VARCHAR(50)  NOT NULL,
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO "user" (user_id, nickname, email, password, role, created_at)
VALUES (1, 'testadmin', 'testadmin123@test.pl',
        '$2a$10$LV8wtoOAffLu7OuBIo/5EelC7B3xz2Du8v9nneLRWDYxOXalh1sPa', 'ADMIN', '2024-11-14 18:54:04.887255');

INSERT INTO "user" (user_id, nickname, email, password, role, created_at)
VALUES (2, 'johndoe', 'johndoe@example.com',
        '$2a$10$LV8wtoOAffLu7OuBIo/5EelC7B3xz2Du8v9nneLRWDYxOXalh1sPa', 'USER', '2024-11-07 13:35:29.346632');

CREATE TABLE FLASHCARD_SET
(
    set_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER      NOT NULL,
    set_name    VARCHAR(100) NOT NULL,
    description TEXT         NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT flashcard_set_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE
);

INSERT INTO FLASHCARD_SET (set_id, user_id, set_name, description, created_at)
VALUES (1, 2, 'Johndoe Set One', 'First set description', '2024-10-10 19:32:38.757753');

INSERT INTO FLASHCARD_SET (set_id, user_id, set_name, description, created_at)
VALUES (2, 2, 'Johndoe Set Two', 'Second set description', '2024-11-13 11:31:24.421905');

CREATE TABLE FLASHCARD
(
    flashcard_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id       INTEGER NOT NULL,
    term         TEXT    NOT NULL,
    definition   TEXT    NOT NULL,
    CONSTRAINT flashcard_set_id_fkey FOREIGN KEY (set_id) REFERENCES FLASHCARD_SET (set_id) ON DELETE CASCADE
);

INSERT INTO FLASHCARD (set_id, term, definition)
VALUES (1, 'S1-Term 1', 'Definition 1'),
       (1, 'S1-Term 2', 'Definition 2'),
       (1, 'S1-Term 3', 'Definition 3'),
       (1, 'S1-Term 4', 'Definition 4'),
       (1, 'S1-Term 5', 'Definition 5'),
       (1, 'S1-Term 6', 'Definition 6'),
       (1, 'S1-Term 7', 'Definition 7'),
       (1, 'S1-Term 8', 'Definition 8'),
       (1, 'S1-Term 9', 'Definition 9'),
       (1, 'S1-Term 10', 'Definition 10');

INSERT INTO FLASHCARD (set_id, term, definition)
VALUES (2, 'S2-Term 1', 'Definition 1'),
       (2, 'S2-Term 2', 'Definition 2'),
       (2, 'S2-Term 3', 'Definition 3'),
       (2, 'S2-Term 4', 'Definition 4'),
       (2, 'S2-Term 5', 'Definition 5'),
       (2, 'S2-Term 6', 'Definition 6'),
       (2, 'S2-Term 7', 'Definition 7'),
       (2, 'S2-Term 8', 'Definition 8'),
       (2, 'S2-Term 9', 'Definition 9'),
       (2, 'S2-Term 10', 'Definition 10');

ALTER TABLE "user"
    ALTER COLUMN user_id RESTART WITH 100;
ALTER TABLE FLASHCARD_SET
    ALTER COLUMN set_id RESTART WITH 100;
ALTER TABLE FLASHCARD
    ALTER COLUMN flashcard_id RESTART WITH 100;
ó