spring:
  application:
    name: Brain Booster Backend

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/brain-booster
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  flyway:
    enabled: true
    locations:
      - classpath:db/migration

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      springframework:
        security: ERROR

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false