spring:
  application:
    name: Brain Booster Backend

  # Hibernate conf
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # PostgreSQL db conf
  datasource:
    url: jdbc:postgresql://localhost:5432/brain-booster
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

# Global path
server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      springframework:
        security: ERROR